# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_10_0.25 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 36 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_10_0.3 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_10_0.35 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 50 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 8 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 9 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.25 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 36 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.3 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.35 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 50 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 5 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 6 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 7 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 8 --num_env_steps 3000000 --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 9 --num_env_steps 3000000 --n_cluster 3


# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000


# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 5 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 6 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 7 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 8 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env navigation --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 9 --num_env_steps 3000000
# python train.py --algo hepn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --structural_entropy True

# python train.py --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 4 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 5 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 3 --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 25 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 26 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 27 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 28 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 29 --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 20 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 21 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 23 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 24 --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --algo hie_mappo --env navigation --lr 0.0005 --critic_lr 0.0005 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 5 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --env navigation --lr 0.0005 --critic_lr 0.0005 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --env navigation --lr 0.0005 --critic_lr 0.0005 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --env navigation --lr 0.0005 --critic_lr 0.0005 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 8 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --env navigation --lr 0.0005 --critic_lr 0.0005 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --algo eghn_mappo --env navigation --lr 0.0002 --critic_lr 0.0002 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 5 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --lr 0.0002 --critic_lr 0.0002 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --lr 0.0002 --critic_lr 0.0002 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --lr 0.0002 --critic_lr 0.0002 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 8 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False --n_cluster 3
# python train.py --algo eghn_mappo --env navigation --lr 0.0002 --critic_lr 0.0002 --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --n_cluster 10 --num_env_steps 3000000 --structural_entropy False --use_eval False --n_cluster 3

# CUDA_VISIBLE_DEVICES=5 python train.py --algo hepn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 36 --use_recurrent_policy False --seed 100 --num_env_steps 10000000 --structural_entropy True --use_eval False --lr 0.0002 --critic_lr 0.0002 --ppo_epoch 5 --critic_epoch 5
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env navigation --exp_name test5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 0 --num_env_steps 3000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env navigation --exp_name test15 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env navigation --exp_name test20 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 2 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo egnnv3_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 3 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo egnnv3_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 4 --num_env_steps 3000000 --structural_entropy False --use_eval False

CUDA_VISIBLE_DEVICES=2 python train.py --algo eghnv2_mappo --env navigation --exp_name s_hidden --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --n_cluster 3 --lr 0.0002 --critic_lr 0.0002 --hidden_sizes [64]
CUDA_VISIBLE_DEVICES=2 python train.py --algo eghnv2_mappo --env navigation --exp_name s_hidden --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 11 --num_env_steps 3000000 --n_cluster 3 --lr 0.0002 --critic_lr 0.0002 --hidden_sizes [128]
CUDA_VISIBLE_DEVICES=2 python train.py --algo eghnv2_mappo --env navigation --exp_name s_hidden --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 12 --num_env_steps 3000000 --n_cluster 3 --lr 0.0002 --critic_lr 0.0002 --hidden_sizes [256]
