# python train.py --algo mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo gat_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo gcn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo graphsage_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 10000000 --structural_entropy False --use_eval False

# python train.py --algo mappo_data_aug --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 24 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo mappo_data_aug --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 25 --num_env_steps 10000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv3_mappo --env pursuit --exp_name test5 --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 5 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv3_mappo --env pursuit --exp_name test15 --obs_mode hepn_local --local_mode False --nr_agents 15 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv3_mappo --env pursuit --exp_name test20 --obs_mode hepn_local --local_mode False --nr_agents 20 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=1 python train.py --algo eghn_mappo --env pursuit --exp_name test40 --obs_mode hepn_local --local_mode True --nr_agents 40 --world_size 100 --obs_radius 50 --use_recurrent_policy False --seed 10 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [96]

CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env pursuit --exp_name test5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 56 --use_recurrent_policy False --seed 7 --num_env_steps 3000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [256]
CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_mappo --env pursuit --exp_name test15 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 5 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]
CUDA_VISIBLE_DEVICES=4 python train.py --algo eghn_mappo --env pursuit --exp_name test20 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 5 --num_env_steps 5000000 --n_cluster 5 --n_rollout_threads 10 --hidden_sizes [128]