# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.25 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 36 --use_recurrent_policy False --seed 4 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.3 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 4 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.35 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 50 --use_recurrent_policy False --seed 4 --num_env_steps 10000000 --n_cluster 3

# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 5 --num_env_steps 10000000 --n_cluster 2
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 5 --num_env_steps 10000000 --n_cluster 5
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 5 --num_env_steps 10000000 --n_cluster 7

# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 8 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 9 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 10 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo eghnv2_mappo --env pursuit --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 11 --num_env_steps 10000000 --n_cluster 3
# python train.py --algo hepn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 0 --num_env_steps 10000000 --structural_entropy True

# python train.py --algo hie_mappo --seed 20 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.001 --critic_lr 0.001 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --seed 21 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.001 --critic_lr 0.001 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --seed 22 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.001 --critic_lr 0.001 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --seed 23 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.001 --critic_lr 0.001 --num_env_steps 10000000 --structural_entropy False --use_eval False
# python train.py --algo hie_mappo --seed 24 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.001 --critic_lr 0.001 --num_env_steps 10000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --seed 25 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --seed 26 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --seed 27 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --seed 28 --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv3_mappo --seed 30 --env pursuit --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --structural_entropy False --use_eval False --use_gae False

# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv2_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 0 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv2_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 1 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv2_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 2 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv2_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 3 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv2_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 4 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False

# CUDA_VISIBLE_DEVICES=5 python train.py --algo hepn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 36 --use_recurrent_policy False --seed 100 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0002 --critic_lr 0.0002 --ppo_epoch 5 --critic_epoch 5 --structural_entropy True

# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 5 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 8 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=5 python train.py --algo egnnv3_mappo --env pursuit --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --num_env_steps 10000000 --structural_entropy False --use_eval False --lr 0.0005 --critic_lr 0.0005 --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True

# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_mappo --env pursuit --exp_name test5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 8 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --train_flag True --use_render False --hidden_sizes [128]
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_mappo --env pursuit --exp_name test10 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 4 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_mappo --env pursuit --exp_name test15 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 4 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_mappo --env pursuit --exp_name test20 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 43 --use_recurrent_policy False --seed 4 --num_env_steps 5000000 --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]

# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --seed 10 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --seed 11 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --seed 12 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --seed 13 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --seed 15 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False

# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test15 --obs_mode hepn_local --local_mode False --nr_agents 15 --world_size 100 --obs_radius 141.4 --seed 21 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env pursuit --exp_name test20 --obs_mode hepn_local --local_mode False --nr_agents 20 --world_size 100 --obs_radius 141.4 --seed 21 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False
# CUDA_VISIBLE_DEVICES=5 python train.py --algo hama_mappo --env pursuit --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 100 --obs_radius 141.4 --seed 21 --num_env_steps 10000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_gae True --use_res False --n_rollout_threads 5