python attack.py --seed 20 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

python attack.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

python attack.py --seed 20 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

python attack.py --seed 20 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

python attack.py --seed 20 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

python attack.py --seed 20 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
python attack.py --seed 20 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
python attack.py --seed 20 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
python attack.py --seed 20 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
python attack.py --seed 20 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct_acc --results results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4