# python train.py --algo eghnv2_mappo --env rendezvous --exp_name tnnls_10_0.25 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 71 --use_recurrent_policy False --seed 3 --num_env_steps 3000000
# python train.py --algo eghnv2_mappo --env rendezvous --exp_name tnnls_10_0.3 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 85 --use_recurrent_policy False --seed 3 --num_env_steps 3000000
# python train.py --algo eghnv2_mappo --env rendezvous --exp_name tnnls_10_0.35 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 100 --use_recurrent_policy False --seed 4 --num_env_steps 3000000
# python train.py --algo eghnv2_mappo --env rendezvous --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 113 --use_recurrent_policy False --seed 11 --num_env_steps 3000000
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 0 --algo eghnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 3000000 --n_cluster 3

# python train.py --algo eghn_mappo --env rendezvous --exp_name tnnls_10_0.25 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 71 --use_recurrent_policy False --seed 3 --num_env_steps 3000000
# python train.py --algo eghn_mappo --env rendezvous --exp_name tnnls_10_0.3 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 85 --use_recurrent_policy False --seed 3 --num_env_steps 3000000
# python train.py --algo eghn_mappo --env rendezvous --exp_name tnnls_10_0.35 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 100 --use_recurrent_policy False --seed 4 --num_env_steps 3000000
# python train.py --algo eghn_mappo --env rendezvous --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 113 --use_recurrent_policy False --seed 11 --num_env_steps 3000000

# python train.py --algo hepn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --structural_entropy True

# CUDA_VISIBLE_DEVICES=3 python train.py --seed 30 --algo hie_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5

# python train.py --seed 24 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --seed 24 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --num_env_steps 3000000 --structural_entropy False --use_eval False --structural_entropy False --use_eval False
# python train.py --seed 28 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --num_env_steps 3000000 --structural_entropy False --use_eval False --use_eval False

# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 1500000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --torus False

# CUDA_VISIBLE_DEVICES=5 python train.py --seed 4 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=5 python train.py --seed 0 --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 1 --critic_epoch 1 --use_huber_loss False --use_gae False

# python train.py --seed 30 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5
# python train.py --seed 25 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 1 --critic_epoch 1

# python train.py --seed 30 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --seed 24 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 3000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=4 python train.py --seed 8 --algo egnnv3_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 9 --algo egnnv3_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 1 --algo egnnv3_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 3000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# python train.py --algo egnnv3_mappo --env rendezvous --exp_name tnnls_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 113 --use_recurrent_policy False --seed 11 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 160 --use_recurrent_policy False --seed 0 --num_env_steps 3000000

# CUDA_VISIBLE_DEVICES=0 python train.py --seed 40 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0008 --critic_lr 0.0008 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=0 python train.py --seed 41 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0008 --critic_lr 0.0008 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=0 python train.py --seed 42 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0008 --critic_lr 0.0008 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=0 python train.py --seed 43 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0008 --critic_lr 0.0008 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=0 python train.py --seed 44 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0008 --critic_lr 0.0008 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4

# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 5 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct_acc --use_gae False
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 6 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct_acc
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 7 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct_acc --use_gae False
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 8 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct_acc
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 9 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct_acc

CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_hidden --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 1500000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --torus False --hidden_sizes [64]
CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_hidden --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 1 --num_env_steps 1500000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --torus False --hidden_sizes [128]
CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_hidden --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 2 --num_env_steps 2000000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --torus False --hidden_sizes [256]