# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 20 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002
# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 21 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002
# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 22 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002
# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 23 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002
# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_mappo --env rendezvous --exp_name ablation --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 24 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002

# CUDA_VISIBLE_DEVICES=4 python train.py --seed 60 --algo egnnv3_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 61 --algo egnnv3_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 62 --algo egnnv3_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 63 --algo egnnv3_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 64 --algo egnnv3_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True

# CUDA_VISIBLE_DEVICES=1 python train.py --seed 30 --algo mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --num_env_steps 1000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 31 --algo mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --num_env_steps 1000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 32 --algo mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --num_env_steps 1000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 33 --algo mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --num_env_steps 1000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=1 python train.py --seed 40 --algo gcn_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 41 --algo gcn_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 42 --algo gcn_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 43 --algo gcn_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 44 --algo gcn_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4

# CUDA_VISIBLE_DEVICES=1 python train.py --algo eghn_mappo --env rendezvous --exp_name test35 --obs_mode hepn_local --local_mode False --n_cluster 5 --nr_agents 35 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 3000000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --torus False
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --seed 10 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --seed 11 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --seed 12 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --seed 13 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --seed 14 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3

CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test5 --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --seed 0 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test15 --obs_mode hepn_local --local_mode False --nr_agents 15 --world_size 200 --obs_radius 282 --seed 0 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test20 --obs_mode hepn_local --local_mode False --nr_agents 20 --world_size 200 --obs_radius 282 --seed 0 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=1 python train.py --algo hmf_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --seed 0 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3