python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.3 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.3 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.3 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.4 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.4 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.4 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.5 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.5 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.5 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.6 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.6 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.6 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.8 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.8 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 0.8 --noise_num 0.0

python attack.py --algo gcn_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 1.0 --noise_num 0.0
python attack.py --algo gat_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 1.0 --noise_num 0.0
python attack.py --algo graphsage_mappo --exp_name test --env navigation --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --structural_entropy False --torus True --dynamics direct --env_num1 0.0 --env_num2 0.0 --use_recurrent_policy False --seed 20 --num_env_steps 2000000 --lr 0.0002 --critic_lr 0.0002 --use_clipped_value_loss True --ppo_epoch 5 --critic_epoch 5 --n_rollout_threads 10 --use_eval False --noise_level 0.0 --noise_num 0.0 --log_dir "./results"  --attack_method obs_noise_all_percp --noise_level 1.0 --noise_num 0.0