# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

# CUDA_VISIBLE_DEVICES=5 python attack_single.py --seed 18 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=5 python attack_single.py --seed 18 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=5 python attack_single.py --seed 18 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
# CUDA_VISIBLE_DEVICES=5 python attack_single.py --seed 18 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
CUDA_VISIBLE_DEVICES=5 python attack_single.py --seed 18 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4


# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4

# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.0
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.1
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.2
# CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack_single.py --seed 18 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.0 --noise_num 0.4