#python train.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct
python train.py --seed 15 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 5000000 --structural_entropy False --use_eval False --dynamics direct
#python train.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct
#python train.py --seed 15 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct
python train.py --seed 15 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct

python model_test.py --algo egnnv2_mappo --seed 23 --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 8000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa

CUDA_VISIBLE_DEVICES=6 python attack.py --seed 30 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct  --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack.py --seed 10 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct  --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3

CUDA_VISIBLE_DEVICES=6 python train.py --seed 21 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_acc
CUDA_VISIBLE_DEVICES=6 python attack.py --seed 21 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
CUDA_VISIBLE_DEVICES=6 python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3

CUDA_VISIBLE_DEVICES=6 python train.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa 
CUDA_VISIBLE_DEVICES=6 python train.py --seed 15 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa 
CUDA_VISIBLE_DEVICES=6 python train.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 600000 --structural_entropy False --use_eval False --dynamics direct_acc --results_dir results_eswa 

CUDA_VISIBLE_DEVICES=6 python train.py --seed 17 --algo mappo_data_aug --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc