# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.0 --noise_num 0.0

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.6
# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.1

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.2

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.3

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.4

# python attack.py --seed 20 --algo egnnv2_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5
# python attack.py --seed 20 --algo gat_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5
# python attack.py --seed 20 --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5
# python attack.py --seed 20 --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5
# python attack.py --seed 20 --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5
# python attack.py --seed 20 --algo mappo_data_aug --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --attack_method obs_noise_all_percp --noise_level 0.05 --noise_num 0.5