CUDA_VISIBLE_DEVICES=6 python train.py --seed 25 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc
CUDA_VISIBLE_DEVICES=6 python train.py --seed 26 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc
CUDA_VISIBLE_DEVICES=6 python train.py --seed 27 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc
CUDA_VISIBLE_DEVICES=6 python train.py --seed 28 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc
CUDA_VISIBLE_DEVICES=6 python train.py --seed 29 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 800000 --structural_entropy False --use_eval False --dynamics direct_acc

# python model_test.py --seed 20 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa
# python train.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct
# python train.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct
# python train.py --seed 16 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 3000000 --structural_entropy False --use_eval False --dynamics direct

# python train.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct
# python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct    
# python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  
# python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_rotation_all --noise_level 0.01 --noise_num 0.2
# python attack_batch.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa 
# python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all --noise_level 0.1 --noise_num 0.2
# python attack_learned.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --noise_level 0.1 --noise_num 0.2
# python attack_learned.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --noise_level 0.1 --noise_num 4.0
# python attack_learned.py --seed 15 --algo gcn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results  --noise_level 0.1 --noise_num 4.0
# python attack_learned.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --noise_level 0.1 --noise_num 4.0

# python play.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  
# python model_test.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  