# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 0 --num_env_steps 3000000 --n_cluster 2
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --n_cluster 5
# python train.py --algo eghnv2_mappo --env navigation --exp_name tnnls_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 57 --use_recurrent_policy False --seed 2 --num_env_steps 3000000 --n_cluster 7
# python train.py --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 11 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 8 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo gcn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --structural_entropy False --use_eval False

# python train.py --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 20 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 21 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 22 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 23 --num_env_steps 3000000 --structural_entropy False --use_eval False
# python train.py --algo mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 24 --num_env_steps 3000000 --structural_entropy False --use_eval False

# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --lr 0.0001 --critic_lr 0.0001 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 30 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --lr 0.0001 --critic_lr 0.0001 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 31 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --lr 0.0001 --critic_lr 0.0001 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 32 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo egnnv2_mappo --env navigation --exp_name ablation --obs_mode hepn_local --local_mode False --nr_agents 10 --lr 0.0001 --critic_lr 0.0001 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 33 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo egnnv2_mappo --env navigation --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --lr 0.0005 --critic_lr 0.0005 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 34 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae True
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv3_mappo --env navigation --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --lr 0.0005 --critic_lr 0.0005 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 34 --num_env_steps 3000000 --structural_entropy False --use_eval False --use_gae True

# CUDA_VISIBLE_DEVICES=1 python train.py --algo eghnv2_mappo --env navigation --exp_name test5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 12 --num_env_steps 2000000 --torus True --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]
# CUDA_VISIBLE_DEVICES=1 python train.py --algo eghnv2_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 12 --num_env_steps 2000000 --torus True --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]


# CUDA_VISIBLE_DEVICES=3 python train.py --algo hama_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 30 --num_env_steps 3000000 --dynamics direct --lr 0.001 --critic_lr 0.001 --use_eval False --n_cluster 4 --n_layers 2 --use_res False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo hama_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 31 --num_env_steps 3000000 --dynamics direct --lr 0.001 --critic_lr 0.001 --use_eval False --n_cluster 4 --n_layers 2 --use_res False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo hama_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 32 --num_env_steps 3000000 --dynamics direct --lr 0.001 --critic_lr 0.001 --use_eval False --n_cluster 4 --n_layers 2 --use_res False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo hama_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 33 --num_env_steps 3000000 --dynamics direct --lr 0.001 --critic_lr 0.0001 --use_eval False --n_cluster 4 --n_layers 1 --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hama_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 50 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_layers 1 --use_res False
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 50 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=0 python train.py --algo graphsage_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 51 --num_env_steps 3000000 --lr 0.0005 --critic_lr 0.0005 --structural_entropy False --use_eval False --use_gea False
# CUDA_VISIBLE_DEVICES=2 python train.py --algo hama_mappo --env navigation --exp_name test5 --obs_mode hepn_local --local_mode False --nr_agents 5 --torus True --world_size 100 --obs_radius 141.5 --seed 10 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
# CUDA_VISIBLE_DEVICES=2 python train.py --algo hama_mappo --env navigation --exp_name test15 --obs_mode hepn_local --local_mode False --nr_agents 15 --torus True --world_size 100 --obs_radius 141.5 --seed 10 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
# CUDA_VISIBLE_DEVICES=2 python train.py --algo hama_mappo --env navigation --exp_name test20 --obs_mode hepn_local --local_mode False --nr_agents 20 --torus True --world_size 100 --obs_radius 141.5 --seed 10 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
# CUDA_VISIBLE_DEVICES=3 python train.py --algo hama_mappo --env navigation --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --torus True --world_size 100 --obs_radius 141.5 --seed 11 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3 --n_rollout_threads 5