# python train.py --algo mappo --env rendezvous --exp_name aaai_5_global --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy True --seed 19 --num_env_steps 3000000 --single_actor False
# python train.py --algo mappo_data_aug --env rendezvous --exp_name aaai_5_global --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 19 --num_env_steps 3000000
# python train.py --algo egnn_mappo --env rendezvous --exp_name aaai_5_global --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 19 --num_env_steps 3000000
# python train.py --algo mappo --env rendezvous --exp_name aaai_5_global --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 19 --num_env_steps 3000000
# python train.py --algo egnnv3_mappo --env rendezvous --exp_name test_5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 200 --obs_radius 113 --use_recurrent_policy False --seed 19 --num_env_steps 3000000
# python train.py --algo egnnv2_mappo --env rendezvous --exp_name test_5 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 200 --obs_radius 113 --use_recurrent_policy False --seed 19 --num_env_steps 3000000
# python train.py --algo hepn_mappo --env rendezvous --exp_name test5 --obs_mode hepn_local --local_mode False --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 1 --num_env_steps 3000000 --structural_entropy True

# CUDA_VISIBLE_DEVICES=1 python train.py --seed 0 --algo gat_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 3000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 0 --algo graphsage_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False
CUDA_VISIBLE_DEVICES=1 python train.py --seed 1 --algo mappo_data_aug --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 3000000 --structural_entropy False --use_eval False
# CUDA_VISIBLE_DEVICES=1 python train.py --seed 0 --algo mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --use_eval False

# CUDA_VISIBLE_DEVICES=6 python train.py --algo egnnv2_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --torus False --num_env_steps 1000000
# CUDA_VISIBLE_DEVICES=6 python train.py --algo egnnv2_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --torus False --num_env_steps 1500000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --n_rollout_threads 10 --hidden_sizes [128] 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv3_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode False --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --torus False --num_env_steps 1500000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --n_rollout_threads 10 --hidden_sizes [128] 

# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_lr --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 1500000 --dynamics direct_acc --lr 0.0001 --critic_lr 0.0001 --torus False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_lr --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 1500000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --torus False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_lr --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 1500000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --torus False
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghnv2_mappo --env rendezvous --exp_name s_lr --obs_mode hepn_local --local_mode False --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 0 --num_env_steps 2000000 --dynamics direct_acc --lr 0.001 --critic_lr 0.001 --torus False