# CUDA_VISIBLE_DEVICES=2 python train.py --seed 35 --algo graphsage_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 36 --algo graphsage_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 37 --algo graphsage_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 38 --algo graphsage_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 39 --algo graphsage_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 4 --critic_epoch 4

# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 99 --use_recurrent_policy False --seed 0 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 99 --use_recurrent_policy False --seed 1 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 99 --use_recurrent_policy False --seed 2 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 99 --use_recurrent_policy False --seed 3 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 200 --obs_radius 99 --use_recurrent_policy False --seed 4 --num_env_steps 1000000 --lr 0.0002 --critic_lr 0.0002 --dynamics direct

# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghnv2_mappo --env rendezvous --exp_name test40 --obs_mode hepn_local --local_mode True --n_cluster 4 --nr_agents 40 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 2 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --hidden_sizes [128] 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test5 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 5 --world_size 200 --obs_radius 200 --use_recurrent_policy False --seed 3 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --train_flag True --use_render False --hidden_sizes [128] 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 10 --world_size 200 --obs_radius 200 --use_recurrent_policy False --seed 2 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --train_flag True --use_render False --hidden_sizes [128] 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test15 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 15 --world_size 200 --obs_radius 200 --use_recurrent_policy False --seed 3 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --train_flag True --use_render False --hidden_sizes [128] 
CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test20 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 20 --world_size 200 --obs_radius 200 --use_recurrent_policy False --seed 2 --num_env_steps 3000000 --dynamics direct --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --train_flag True --use_render False --hidden_sizes [128] 