# python train.py --algo egnn_mappo --env navigation --exp_name aaai_5_0.4 --obs_mode hepn_local --local_mode True --nr_agents 5 --world_size 100 --obs_radius 56 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --use_hpn False
# python train.py --algo egnn_mappo --env navigation --exp_name aaai_10_0.4 --obs_mode hepn_local --local_mode True --nr_agents 10 --world_size 100 --obs_radius 56 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --use_hpn False
# python train.py --algo egnn_mappo --env navigation --exp_name aaai_15_0.4 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 56 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --use_hpn False
# python train.py --algo egnn_mappo --env navigation --exp_name aaai_20_0.4 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 56 --use_recurrent_policy False --seed 10 --num_env_steps 3000000 --use_hpn False

# CUDA_VISIBLE_DEVICES=0 python train.py --algo eghnv2_mappo --env navigation --exp_name test15 --obs_mode hepn_local --local_mode True --nr_agents 15 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 13 --num_env_steps 2000000 --torus True --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]
# CUDA_VISIBLE_DEVICES=0 python train.py --algo eghnv2_mappo --env navigation --exp_name test20 --obs_mode hepn_local --local_mode True --nr_agents 20 --world_size 100 --obs_radius 141.5 --use_recurrent_policy False --seed 12 --num_env_steps 2000000 --torus True --n_cluster 3 --n_rollout_threads 10 --hidden_sizes [128]


CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 3 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 4 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 5 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 3 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3
# CUDA_VISIBLE_DEVICES=0 python train.py --algo hmf_mappo --env navigation --exp_name test10 --obs_mode hepn_local --local_mode False --nr_agents 10 --torus True --world_size 100 --obs_radius 141.5 --seed 104 --num_env_steps 3000000 --dynamics direct --lr 0.0005 --critic_lr 0.0005 --use_eval False --n_cluster 3