#!/bin/sh

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 0 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 0 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 0 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 1 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 1 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 12 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.001 --critic_lr 0.0005

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 2 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 2 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 13 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.001 --critic_lr 0.0005

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 3 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 3 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 14 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.001 --critic_lr 0.0005

# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 4 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0002 --num_env_steps 10000000
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 4 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 
# python train.py --algo eghn_critic_mappo --env smacv2 --exp_name rnn --seed 15 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 5 --use_recurrent_policy True --lr 0.001 --critic_lr 0.0005

# python train.py --algo eghnv2_mappo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 10000000 --episode_length 200

# CUDA_VISIBLE_DEVICES=4 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 17 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 2 --critic_num_mini_batch 2
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 15 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 2 --critic_num_mini_batch 2
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 15 --use_eval True --eval_episodes 40 --map_name zerg_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 2 --critic_num_mini_batch 2

# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 12 --use_eval True --eval_episodes 50 --map_name terran_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.001 --critic_lr 0.0005 --num_env_steps 10000000 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 12 --use_eval True --eval_episodes 50 --map_name protoss_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.001 --critic_lr 0.0005 --num_env_steps 10000000 
# CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_critic_mappo --env smacv2 --exp_name test --seed 12 --use_eval True --eval_episodes 50 --map_name zerg_5_vs_5 --n_rollout_threads 10 --n_cluster 3 --use_recurrent_policy False --lr 0.001 --critic_lr 0.0005 --num_env_steps 10000000 


# smacv2参数设置
# CUDA_VISIBLE_DEVICES=6 python train.py --algo eghn_critic_happo --env smacv2 --exp_name test --seed 11 --use_eval True --eval_episodes 40 --map_name zerg_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=5 python train.py --algo eghn_critic_happo --env smacv2 --exp_name test --seed 13 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=7 python train.py --algo eghn_critic_happo --env smacv2 --exp_name test --seed 9 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 2 --critic_num_mini_batch 2


# CUDA_VISIBLE_DEVICES=1 python train.py --algo egnn_critic_mappo --env smacv2 --exp_name test --seed 0 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 10 --episode_length 200 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=1 python train.py --algo egnn_critic_mappo --env smacv2 --exp_name test --seed 1 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 10 --episode_length 200 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=1 python train.py --algo egnn_critic_mappo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 10 --episode_length 200 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=1 python train.py --algo egnn_critic_mappo --env smacv2 --exp_name test --seed 3 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 10 --episode_length 200 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
CUDA_VISIBLE_DEVICES=5 python train.py --algo egnn_critic_mappo --env smacv2 --exp_name test --seed 4 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 10 --episode_length 200 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1