# python train.py --algo hepn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 9 --num_env_steps 3000000 --structural_entropy True
# python train.py --algo hepn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --num_env_steps 10000000 --structural_entropy True
# python train.py --algo hepn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 9 --num_env_steps 3000000 --structural_entropy True

# python train.py --algo hepn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 7 --num_env_steps 3000000 --structural_entropy True
# python train.py --algo hepn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --num_env_steps 10000000 --structural_entropy True
# python train.py --algo hepn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 7 --num_env_steps 3000000 --structural_entropy True

# python train.py --algo hepn_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 6 --num_env_steps 3000000 --structural_entropy True
# python train.py --algo hepn_mappo --env pursuit --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --num_env_steps 10000000 --structural_entropy True
# python train.py --algo hepn_mappo --env navigation --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 100 --obs_radius 141.4 --use_recurrent_policy False --seed 6 --num_env_steps 3000000 --structural_entropy True

# CUDA_VISIBLE_DEVICES=5 python train.py --algo hie_critic_mappo --env smacv2 --exp_name ablation --seed 10 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 10 --episode_length 200 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1 --n_layers 1
# CUDA_VISIBLE_DEVICES=5 python train.py --algo hie_critic_mappo --env smacv2 --exp_name ablation --seed 11 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 10 --episode_length 200 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1 --n_layers 1
# CUDA_VISIBLE_DEVICES=5 python train.py --algo hie_critic_mappo --env smacv2 --exp_name ablation --seed 12 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 10 --episode_length 200 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1 --n_layers 1
# CUDA_VISIBLE_DEVICES=5 python train.py --algo hie_critic_mappo --env smacv2 --exp_name ablation --seed 13 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 10 --episode_length 200 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1 --n_layers 1
# CUDA_VISIBLE_DEVICES=5 python train.py --algo hie_critic_mappo --env smacv2 --exp_name ablation --seed 14 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 10 --episode_length 200 --n_cluster 3 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1 --n_layers 1

# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_critic_happo --env smacv2 --exp_name test --seed 24 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 15000000 --clip_param 0.05 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=3 python train.py --algo eghn_critic_happo --env smacv2 --exp_name test --seed 25 --use_eval True --eval_episodes 40 --map_name protoss_5_vs_5 --n_rollout_threads 20 --episode_length 160 --n_cluster 3 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 15000000 --clip_param 0.05 --actor_num_mini_batch 1 --critic_num_mini_batch 1

# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnn_critic_happo --env smacv2 --exp_name test --seed 0 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.05 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnn_critic_happo --env smacv2 --exp_name test --seed 1 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnn_critic_happo --env smacv2 --exp_name test --seed 2 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnn_critic_happo --env smacv2 --exp_name test --seed 3 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1
# CUDA_VISIBLE_DEVICES=2 python train.py --algo egnn_critic_happo --env smacv2 --exp_name test --seed 4 --use_eval True --eval_episodes 40 --map_name terran_5_vs_5 --n_rollout_threads 20 --episode_length 160 --use_recurrent_policy True --lr 0.0005 --critic_lr 0.0005 --num_env_steps 10000000 --clip_param 0.2 --actor_num_mini_batch 1 --critic_num_mini_batch 1

# CUDA_VISIBLE_DEVICES=2 python train.py --seed 30 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 31 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 32 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 33 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5
# CUDA_VISIBLE_DEVICES=2 python train.py --seed 34 --algo gat_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode True  --nr_agents 10 --world_size 200 --obs_radius 98.7 --use_recurrent_policy False --lr 0.0001 --critic_lr 0.0001 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5

# CUDA_VISIBLE_DEVICES=4 python train.py --seed 100 --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 101 --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 102 --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 103 --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True
# CUDA_VISIBLE_DEVICES=4 python train.py --seed 104 --algo egnnv2_mappo --env rendezvous --exp_name tase --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0005 --critic_lr 0.0005 --num_env_steps 1000000 --structural_entropy False --use_eval False --ppo_epoch 5 --critic_epoch 5 --use_huber_loss True --use_gae True

CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test5 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 5 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 5 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0002 --critic_lr 0.0002 --n_rollout_threads 10 --torus False --hidden_sizes [128] 
CUDA_VISIBLE_DEVICES=2 python train.py --algo eghn_mappo --env rendezvous --exp_name test15 --obs_mode hepn_local --local_mode True --n_cluster 3 --nr_agents 15 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 5 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --n_rollout_threads 10 --torus False --hidden_sizes [128] 
CUDA_VISIBLE_DEVICES=4 python train.py --algo eghn_mappo --env rendezvous --exp_name test20 --obs_mode hepn_local --local_mode True --n_cluster 4 --nr_agents 20 --world_size 200 --obs_radius 282 --use_recurrent_policy False --seed 5 --num_env_steps 1000000 --dynamics direct_acc --lr 0.0005 --critic_lr 0.0005 --n_rollout_threads 10 --torus False --hidden_sizes [128] 