# 0不攻击
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method none --noise_level 0.0 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method none --noise_level 0.0 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method none --noise_level 0.0 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method none --noise_level 0.0 --noise_num 0.0
# 1高斯噪声攻击-传感器数据-全局-0.1
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.1 --noise_num 0.0
# 2高斯噪声攻击-传感器数据-全局-0.2
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_all_percp --noise_level 0.2 --noise_num 0.0
# 3高斯噪声攻击-传感器数据-单体-0.2
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.2 --noise_num 0.0
# 4高斯噪声攻击-传感器数据-单体-0.4
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_noise_single_percp --noise_level 0.4 --noise_num 0.0
# 5白盒FGSM攻击-传感器数据-全局-0.1
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.1 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.1 --noise_num 0.0
# 6白盒FGSM攻击-传感器数据-全局-0.2
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_all_percp --noise_level 0.2 --noise_num 0.0
# 7白盒FGSM攻击-传感器数据-单体-0.2
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.2 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.2 --noise_num 0.0
# 8白盒FGSM攻击-传感器数据-单体-0.4
python attack.py --seed 15 --algo egnnv2_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo gat_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo graphsage_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.4 --noise_num 0.0
python attack.py --seed 15 --algo mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 1000000 --structural_entropy False --use_eval False --dynamics direct --results_dir results_eswa  --attack_method obs_grd_single_percp --noise_level 0.4 --noise_num 0.0
