#python train.py --seed 15 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3 
#python train.py --seed 16 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python train.py --seed 17 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python train.py --seed 18 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python train.py --seed 19 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python play.py --seed 17 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python play.py --seed 16 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3
python model_test.py --seed 16 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3

python attack.py --seed 16 --algo egnn_mix_mappo --env rendezvous --exp_name test --obs_mode hepn_local --local_mode False --nr_agents 10 --world_size 200 --obs_radius 282 --use_recurrent_policy False --lr 0.0002 --critic_lr 0.0002 --num_env_steps 2000000 --structural_entropy False --use_eval False --dynamics direct_asym --env_num1 0.3